### ISSUE TITLE
App Displays a black blank page, when the back button is pressed 

### ISSUE THREAD

**Issue by isreal6ix** [nicklasaven/TileLess#13]
***Expected Behavior***

The app should direct users to the homepage view of the app

***Actual Behavior***

The app shows a back blank page when users presses the back button 

***Test Tools**

* Operating system : Android 6.0
* Phone : Infinix hot s
* TilelessMap 0.1.2

***How to produce the bug***

Open the app, once it has opened and loads the device folders, press the back button on your device.  And it would be static, displaying a black blank page 

*Recording of the bug is shown below......*

https://youtu.be/2yfLcvI2psI

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/app-displays-a-black-blank-page-when-the-back-button-is-pressed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by nicklasaven** [comment]
Thanks!
I will look at it.

I am not an Android dev so I have just ported my C-code ass quick and dirty as possible (SDL really did the job)

But there should of course be a proper home screen.

Now is also the description and some instructions available on f-droid. I had messed up the fastlane directory at first release so some important info was missing.

**Comment by nicklasaven** [comment]
I have added a homescreen and back button seems to work as expected to that.
https://github.com/TilelessMap/TilelessMap/releases/tag/v0.1.5

It should be available on f-droid in a few days, I see they have started the build process again.
Take a look when it is available, and you can close this if it looks ok
