### ISSUE TITLE
Could you tell me how to make a map like “boston19.tileless”？

### ISSUE THREAD

**Issue by zlel** [nicklasaven/TileLess#8]
I have only shp files in my hand，and I want to convert it to sqlite3 file。

**Comment by nicklasaven** [comment]
Hi, the tools I have uses PostGIS. Do you have experience with PostGIS?

If so, load the data in PostGIS.

You will also need the extension pg_tileless:
https://github.com/nicklasaven/pg_tileless

I have only compiled it in Linux, do you have Linux?

I will put some example sql in the Readme, but have not had time. 

But it will look something like

`select * from tileless.pack_twkb_polygon(tbl:='boston.landuse19', geom_fld:='geom', id_fld:='gid',other_flds:='lucode', db:='/tmp/boston19.sqlite',layer_name:='boston_landuse', prefix:='boston_landuse', n_decimals:=0, subdivide:= true);`

That is for landuse map in Boston. 

As you see things are not user friendly yet. Sorry about that. But I still but the work on getting some basic functionality in place and making it robust.

**Comment by zlel** [comment]
thank you for your reply. 
I have already installed postgis and compiled pg_tileless on ubuntu. but there was an error when I called tileless.pack_twkb_polygon. 

--------------------------------------------------------------------------------------------
postgres=# \c gisdb
You are now connected to database "gisdb" as user "postgres".
gisdb=# select * from tileless.pack_twkb_polygon(tbl:='planet_osm_line', geom_fld:='geom', id_fld:='gid',other_flds:='lucode', db:='/tmp/gisdb.sqlite',layer_name:='planet_osm_line', prefix:='planet_osm_line', n_decimals:=0, subdivide:= true);
NOTICE: sequence "planet_osm_line_sequence" does not exist, skipping
NOTICE: Starta spatial ordering 2017-07-01 13:18:26.608658+00s
NOTICE: table "planet_osm_line_ordered" does not exist, skipping
ERROR: column "gid" does not exist
LINE 4: (select gid, geom, st_centroid(geom) centr ,lucode
  ^
QUERY: drop table if exists tmp.planet_osm_line_ordered;
create table tmp.planet_osm_line_ordered as
select * from
(select gid, geom, st_centroid(geom) centr ,lucode
from planet_osm_line) a
order by round(st_x(centr)/10000),round(st_y(centr)/10000);

--------------------------------------------------------------------------------------------

It should be in the postgis table does not have the corresponding columns, how do you load shp or osm files into the postgis, and with the columns like ‘geom', 'gid', 'lucode'?

**Comment by nicklasaven** [comment]
Just change the field names in the function call. Where I have used gid you put some id that you want to use in your application. It doesn't have to be unique. Pg_tileless will create a twkb_id that will be unique and keep things together. Where I have used geom, just put the name of your geometry column. Where I have put lucode, you add zero to many comma separated field names that you want to nring to the sqlit db. Lucode is for styling. 

And 1 more thing. If it is lines that you want to pack, don't use the polygon function. I am not by the computor, but look in the sql file in pg_tileless you will find a function with linestring in the name instead of polygon. I think you can figure out how to use it from looking at the parameters names.

**Comment by zlel** [comment]
Thanks for your instruction.
I have generated these tables.

Planet_osm_line
planet_osm_line_idx_geom
planet_osm_line_idx_geom_node
planet_osm_line_idx_geom_parent
planet_osm_line_idx_geom_rowid

but, dbs, fonts, geometry_columns, init_box, layers, styles, text_conf, these tables are not automatically generated. need to be generated manually?

**Comment by nicklasaven** [comment]
Yes, you will have to fill them up manually for now. The fonts table is a little special. It contains a binary blob of a true type font. So the easiest is to copy that from the Boston db. attach the Boston db to your new db and run "create table fonts as select * from boston.fonts;" (if you name the attached db "boston") 

Alternatively you make a copy of the boston db, remove the boston tables and run the pg_tileless scripts against that db. Then you get your new table in that db and just have to adjust geometry_columns and Co accordingly.

Good work getting through this :-) 

Just continue asking when you get stuck.

**Comment by zlel** [comment]
Now, I can use "tileless.pack_twkb_polygon" to convert polygon layer, and also use "tileless.pack_twkb_linestring" to convert line layer, but I don't know how to convert point layer up to this time. For example I have a text layer, How can I use this tool to do the conversion?

**Comment by nicklasaven** [comment]
I close this since textlayer creation is in another issue

(Should have had an e-mail list instead for those things)
