### ISSUE TITLE
TileLess compile error

### ISSUE THREAD

**Issue by zlel** [nicklasaven/TileLess#9]
When I compile the program, there are some errors.

error: redefinition error at twkb_decode.c
> uint32_t ndims = theLayer->n_dims;

I have fixed this error like this, but I don't know whether it is right.
> /\*uint32_t\*/ ndims = theLayer->n_dims;

then, I got another error.
error: undefined reference to 'wn_PnPoly'  at info.c

TileLess's code has not finished yet ?

**Comment by nicklasaven** [comment]
It compiles for me
There are a lot of warnings about unused variables, but that is ok. I will clean that up when the identify part is in place.

So, make sure you have the "latest code" with git pull. 
Run `make clean` before you run `make`.

Or clone the repo again ad get everything fresh.

wn_PnPoly is defined in info.h  

About the redefinition of ndims I cannot see it in the code. I think you don't have the latest code. I have done some committing that have broken it, but the latest should be ok. So try to get it fresh and test please, and tell me the outcome.

**Comment by zlel** [comment]
I used the newest code and now errors have resolved.  But I can't open the map file that dowloaded from "http://twkb.jordogskog.no/", and I found that the geometry_columns table has appended a new field called "n_dims",  what is the meaning of this field? I can manually add this field, What kind of value is correct?

**Comment by nicklasaven** [comment]
Ah, yes you are right, sorry.
The files at twkb.jordogskog.no is behind.

There should be a field n_dims as you say, telling how many dimensions the data have.
So run:
```
alter table geometry_columns add column n_dims int;
update geometry_columns set n_dims = 2;

```

**Comment by nicklasaven** [comment]
Is this solved?
Can I close it?
